### Get all movies
GET http://localhost:5000/movies

### Get movie
GET http://localhost:5000/movies/5fa7a3d7d78a80cdeb9fddbe

### Add movie
POST http://localhost:5000/movies
content-type: application/json

{
  "casts": [
    "Jake Gyllenhaal"
  ],
  "genres": [
    "Drama",
    "Biography"
  ],
  "name": "October Sky"
}
### Update movie
PUT http://localhost:5000/movies/5fa7a3d7d78a80cdeb9fddbe
content-type: application/json

{
  "casts": [
    "Jake Gyllenhaal"
  ],
  "genres": [
    "Drama"
  ],
  "name": "October Sky"
}

### Delete movie
DELETE http://localhost:5000/movies/2